### PR TITLE
Clock and lightning strike distance improvements

### LINKED ISSUE #605: Give user enough time on clock sync
Give at least 15 seconds, even of that means going to the next minute

### PR DESCRIPTION
**Pull request by qwerty287**
This resolves #605 and (partially) #602

### CODE REVIEW

**Comment by kylecorry31** [comment]
Thanks, I'm going to hold off on merging this until 2.1.0 is released tomorrow, and I'll test it after that

**Comment by qwerty287** [comment]
Ok, I made a small change on the lightning strike tool, so you can reset it by pressing the lightning button (only if you already pressed both buttons once) - 1. do you want to add it and 2. if you want to add it, should I add it to this PR?

**Comment by kylecorry31** [comment]
Sure, that sounds fine and yes you can add it to this PR

**Comment by qwerty287** [comment]
OK, I'll do this later today (or maybe tomorrow).

**Comment by qwerty287** [comment]
> Sure, that sounds fine and yes you can add it to this PR
> 
> Although, I may change that tool a little - I finally got to use it out for real the other day and thought the usability could be improved

I never used it in reality, but I wouldn't know what could be improved. Which improvements do you've considered?

**Comment by kylecorry31** [comment]
I'm not 100% sure, but I think I want it to be more like the cliff height tool with 1 button (states: off/waiting for thunder, on/heard thunder, off/waiting for thunder/saw lighting). I found it a little difficult to ensure my finger was placed over the lightning button after hearing thunder.

**Pull request merged**
