### PR TITLE
Update CompassDirection.kt

### PR DESCRIPTION
**Pull request by efraletti**
Fix southwest to show as SW instead of SE.

### CODE REVIEW

**Comment by kylecorry31** [comment]
Wow, can't believe I never noticed that. Thanks!

**Comment by efraletti** [comment]
All right!

The file I updated can have more floats declared, to implement all cardinal directions?

I did not check other files in the program, but maybe we can do something like this:

https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Brosen_windrose.svg/1200px-Brosen_windrose.svg.png

Thank you for the excellent app.

**Comment by kylecorry31** [comment]
I'm not sure how I feel about having those intercardinal directions such as NNW. I personally prefer just having the NW level of direction. 

Do you think that having directions such as NNW would be useful? I could always add a setting for that.

Thank you!

**Comment by efraletti** [comment]
I just tested the app with correct SW indication, and my thoughts are that maybe those additional directions will bloat the compass.

An option to show it would make a nice extra feature though, if one desires, who knows. In nautical setting it sure is important.

**Pull request merged**
