### PR TITLE
Sighting compass

### PR DESCRIPTION
**Pull request by qwerty287**
The user can now change the zoom ratio with a SeekBar below the camera view. This should resolve the last problems on the scaled/cropped image, right? 
And I fixed a bug, the camera would ran in the background if you leave the linear compass view (with the camera view enabled).

### CODE REVIEW

**Comment by kylecorry31** [comment]
Thanks, I may end up moving this to settings, but I'll try it out later

**Comment by kylecorry31** [comment]
After experimenting with this, your implementation is good, I agree the seek bar should be there rather than in settings (if possible, it would be nice to turn off image stabilization - at least on my phone it makes the movement too smooth while moving to the point that it doesn't match up with the actual motion of the device.

**Comment by qwerty287** [comment]
OK, I'll see how I can implement this

**Comment by qwerty287** [comment]
I don't know if there's any other library to control this, but I didn't find anything on image stabilization in Android developer reference related to CameraX.

**Pull request merged**
