### PR TITLE
International whistle signals

### LINKED ISSUE #443: [Whistle] Add international whistle codes
Where are you? : 1
Acknowledged: 1
Come here: 2
Help: 3

### PR DESCRIPTION
**Pull request by qwerty287**
Should resolve #443 
The loop works - if you start a signal, it's repeated until stopped. I don't know why you shouldn't add it, if you don't need it, you don't have to use it and it's a little bit a "hidden" feature.

### CODE REVIEW

**Comment by kylecorry31** [comment]
Thanks, I'll test it out and consider it

**Comment by kylecorry31** [comment]
So upon reviewing this, yes it is okay to add this, but I have one change that I would need to be implemented: only the help signal should be run as a loop, the others should just run through their sequence once and stop. Also, not that as part of the work (#561) I'm doing, the help whistle will be run differently (it is being spawned by a new foreground service, rather than running within the whistle fragment). 

I believe that should be as easy as replacing true with false when playing the whistle, but I haven't tested that out here.

**Comment by qwerty287** [comment]
The problem is, that the button stays on if you do this. I don't think it's a problem if it's looped, but it's not necessary that it runs in the background

**Comment by kylecorry31** [comment]
Okay, yeah the correct behavior would be to turn off the button state when the whistle is done. There is a third parameter on the play method which is a function called when the sound sequence is done playing - that can be used to turn the button back off.

**Comment by kylecorry31** [comment]
Looks good, thanks!

**Pull request merged**
