### PR TITLE
#2327 update analog image background color

### PR DESCRIPTION
**Pull request by muryno**
#2327

### CODE REVIEW

**Comment by kylecorry31** [comment]
Thank you, looks good. Just to confirm, are you planning on doing a second PR for #2327 to use the CanvasView in ClockView?

**Comment by muryno** [comment]
I can create another pr for it... wanted to get this working first before using the class...
The idea is to optimise the code right ?

**Comment by kylecorry31** [comment]
> I can create another pr for it... wanted to get this working first before using the class... The idea is to optimise the code right ?

Sounds good. No it is not code optimization, it is switching from the low level canvas API to use the CanvasView class (there are a few examples in Trail Sense of it being used if you search for references to that class). It should do the same thing, just not use the lower level canvas / paint APIs.

**Comment by muryno** [comment]
gottach... I will update and create new PR soon

**Pull request merged**
