### PR TITLE
#2108 move pressure history settings to weather

### LINKED ISSUE #2108: Move pressure history setting to weather settings
This is a display only setting, and it is only used on the weather tool - therefore shouldn't be in the barometer settings.

### PR DESCRIPTION
**Pull request by muryno**
fixes #2108 

https://github.com/kylecorry31/Trail-Sense/assets/26343440/c7c3dc13-f32f-465a-b289-c442b4b86859

### CODE REVIEW

**Comment by muryno** [comment]
@kylecorry31  I left **CalibrateBarometerFragment** and **barometer_calibration.xml** incase they want to be couple to another module

**Comment by kylecorry31** [comment]
Hi, thank you for taking the time to do this. 

I will need to think about this for a little bit to see if it makes sense to move all these settings to the Weather settings - the intent of #2108 was that only the "Pressure history" setting would be moved (so the chart, sea level, smoothing, and factor in temperature would remain on the barometer settings)

**Comment by kylecorry31** [comment]
I've decided that only the "Pressure history" setting should be moved to the Weather settings. The other settings and chart should remain on the Barometer settings. Can you make this change?

**Comment by muryno** [comment]
cool.. I will update the code

**Comment by muryno** [comment]
@kylecorry31  is this the expected UI

WhatsApp Image 2024-03-11 at 23 32 01
WhatsApp Image 2024-03-11 at 23 32 01 (1)

**Comment by kylecorry31** [comment]
Almost, can you keep it grouped with General instead of Barometer?

**Comment by muryno** [comment]
Screenshot 2024-03-12 at 04 12 46

**Comment by kylecorry31** [comment]
Looks good, thanks!

**Pull request merged**
