### PR TITLE
Upgrade to Material You

### PR DESCRIPTION
**Pull request by ebraminio**
Upgrading to an alpha library for sure should be avoided where possible so not expecting to having this merged but now that trail sense's UI is upgraded to Material, maybe having this sooner (in beta for example) would be better so to have an UI upgrade only once, but we should also be careful as this can possibly have some stability issues.

Anyway, guess is worth to try locally at least as there are interesting changes here :)

### CODE REVIEW

**Comment by kylecorry31** [comment]
Thanks, I'll check this out - but as you mentioned, I'm going to hold off until it is stable.

**Comment by ebraminio** [comment]
The material library is now beta so I added dynamic colors support using it which will look like this; the easiest way to see it is to use the just released Sv2 Android image and hope you find interesting as well,

https://user-images.githubusercontent.com/833473/141472535-e80dcae1-4e30-4130-b8e0-64231daacf47.mov

**Comment by kylecorry31** [comment]
Thanks! Just a few things:
- I don't think I want dynamic colors to be on by default - do you know if there is a way to toggle this from Kotlin?
- When dynamic colors is on, most of the colorPrimary tinted icons/labels should be that color
- Can the title bar which says "Trail Sense" be removed? (like the NoActionBar style Trail Sense uses now)

**Comment by ebraminio** [comment]
Good points

> I don't think I want dynamic colors to be on by default - do you know if there is a way to toggle this from Kotlin?

Done. The new version has dynamic colors behind `if (false) DynamicColors.applyIfAvailable(this)` which if that `if (false)` removed it works again.

> When dynamic colors is on, most of the colorPrimary tinted icons/labels should be that color

This just needs the whole project to use R.attr.colorAccent instead R.color.colorAccent.

> Can the title bar which says "Trail Sense" be removed? (like the NoActionBar style Trail Sense uses now)

Done.

**Comment by kylecorry31** [comment]
Thanks for the changes! I'm still going to hold off on merging this in until 1.5.0 is a stable release though, but it is looking good

**Comment by ebraminio** [comment]
> Thanks for the changes! I'm still going to hold off on merging this in until 1.5.0 is a stable release though, but it is looking good

Sure, sure

**Comment by kylecorry31** [comment]
Added this issue to track the dynamic colors: #1008
Added this issue to track Material3: #1009

**Comment by kylecorry31** [comment]
Known issues (can be addressed after merge with #1009):

- [ ] Switches have a purple background when ON
- [ ] Bottom sheet has an orange tint (should be background color
- [ ] Text inputs are outlined rather than filled (not sure if this is actually an issue - I kind of like the outline view, I'll need to play around with it)
- [ ] QR card has an outline
- [ ] The bottom navigation is a little too tall (preferably it is the same size as the current version)

**Pull request merged**
